POST https://node-do-zero-poze.onrender.com/videos
Content-Type: application/json

{
    "title": "Video 1",
    "description": "Esse é o primeiro video",
    "duration": 180
}


###
GET https://node-do-zero-poze.onrender.com/videos


###
PUT https://node-do-zero-poze.onrender.com/videos/c697d501-6a7c-4b5e-af40-266f2f80a4fc
Content-Type: application/json

{
    "title": "Video solitario",
    "description": "Esse é o segundo video",
    "duration": 180
}

###
DELETE https://node-do-zero-poze.onrender.com/videos/08044b03-b7d7-4d64-93ea-49d16de28d50


